/**
 * Database Types
 * Auto-generated TypeScript types from Supabase schema
 *
 * To regenerate these types, run:
 *   npm run gen:types
 *
 * This requires:
 * 1. Supabase local instance running (supabase start)
 * 2. All migrations applied (supabase db reset)
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder types - will be generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.types.ts

export interface Database {
  public: {
    Tables: {
      role: {
        Row: {
          id: string
          code: string
          name: string
          scope: 'platform' | 'tenant' | 'household' | 'security'
          hierarchy_level: number
          permissions: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          name: string
          scope: 'platform' | 'tenant' | 'household' | 'security'
          hierarchy_level: number
          permissions?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          name?: string
          scope?: 'platform' | 'tenant' | 'household' | 'security'
          hierarchy_level?: number
          permissions?: Json
          created_at?: string
          updated_at?: string
        }
      }
      tenant: {
        Row: {
          id: string
          name: string
          slug: string
          subscription_plan: Json
          status: 'active' | 'trial' | 'suspended' | 'cancelled'
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          subscription_plan?: Json
          status?: 'active' | 'trial' | 'suspended' | 'cancelled'
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          subscription_plan?: Json
          status?: 'active' | 'trial' | 'suspended' | 'cancelled'
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      user_profile: {
        Row: {
          id: string
          auth_user_id: string
          first_name: string
          last_name: string
          contact_number: string | null
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          auth_user_id: string
          first_name: string
          last_name: string
          contact_number?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          auth_user_id?: string
          first_name?: string
          last_name?: string
          contact_number?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      tenant_user: {
        Row: {
          id: string
          tenant_id: string
          user_profile_id: string
          role_id: string
          is_active: boolean
          permissions: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          user_profile_id: string
          role_id: string
          is_active?: boolean
          permissions?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          user_profile_id?: string
          role_id?: string
          is_active?: boolean
          permissions?: Json
          created_at?: string
          updated_at?: string
        }
      }
      household: {
        Row: {
          id: string
          tenant_id: string
          address: string
          lot_number: string | null
          block_number: string | null
          sticker_quota: number
          status: 'active' | 'inactive' | 'suspended'
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          address: string
          lot_number?: string | null
          block_number?: string | null
          sticker_quota?: number
          status?: 'active' | 'inactive' | 'suspended'
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          address?: string
          lot_number?: string | null
          block_number?: string | null
          sticker_quota?: number
          status?: 'active' | 'inactive' | 'suspended'
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      resident: {
        Row: {
          household_id: string
          tenant_user_id: string
          has_visiting_rights: boolean
          has_signatory_rights: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          household_id: string
          tenant_user_id: string
          has_visiting_rights?: boolean
          has_signatory_rights?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          household_id?: string
          tenant_user_id?: string
          has_visiting_rights?: boolean
          has_signatory_rights?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      residential_community_config: {
        Row: {
          tenant_id: string
          rules_and_guidelines: Json
          curfew_settings: Json
          gate_operating_hours: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          rules_and_guidelines?: Json
          curfew_settings?: Json
          gate_operating_hours?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          tenant_id?: string
          rules_and_guidelines?: Json
          curfew_settings?: Json
          gate_operating_hours?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Functions: {
      get_user_tenants: {
        Args: Record<string, never>
        Returns: Array<{
          tenant_id: string
          tenant_name: string
          tenant_slug: string
          tenant_status: string
          role_id: string
          role_code: string
          role_name: string
          is_active: boolean
          joined_at: string
        }>
      }
      switch_tenant_context: {
        Args: { p_tenant_id: string }
        Returns: Json
      }
      assign_user_to_tenant: {
        Args: {
          p_user_profile_id: string
          p_tenant_id: string
          p_role_id: string
          p_permissions?: Json
        }
        Returns: Json
      }
      check_user_permission: {
        Args: { p_permission_key: string }
        Returns: boolean
      }
      check_user_permissions: {
        Args: { p_permission_keys: string[] }
        Returns: Array<{
          permission_key: string
          has_permission: boolean
        }>
      }
      get_current_user_permissions: {
        Args: Record<string, never>
        Returns: Json
      }
      validate_current_session: {
        Args: Record<string, never>
        Returns: Json
      }
    }
  }
}
